services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /Users/zz_mm/Desktop/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    #privileged: true
    #network_mode: host
    networks:
      - traefik
      - homeassistant
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.zzbyte.dev`)"
        - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
  matter-server:
    container_name: matter-server
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    restart: unless-stopped
    security_opt:  
      - apparmor=unconfined
    #ports:
     # - 5580:5580
    #network_mode: host # Or a specific network if needed
    volumes:
      - /Users/zz_mm/Desktop/home-assistant/matter_data:/data # Map a host directory for persistent data
      - /run/dbus:/run/dbus:ro
    environment:
      - TZ=Asia/Yerevan
    networks:
      - homeassistant
networks:
  homeassistant:
  traefik:
    external: true
